image: alpine

before_script:
- apk update
- apk add doxygen
## Uncomment the following line if you use graphviz dot graphs
#- apk add ttf-freefont graphviz

test:
  script:
  - doxygen docs/Doxyfile
  #- doxygen docs/mavs_python_Doxyfile
  except:
  - master
  
pages:
  script:
  - doxygen docs/Doxyfile
  #- doxygen docs/mavs_python_Doxyfile
  - mv docs/html/ public/
  #- mv docs/python/html public/mavs_python
  artifacts:
    paths:
    - public
  only:
  - master
